name: stronz_cast
description: "Dart Casting library used in StronzLabs's applications"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  cast: ^2.1.0
  castscreen:
    git: https://github.com/Bonfra04/dart_castscreen.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
